apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: '7.*'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  interval: 5m
  timeout: 5m
  targetNamespace: kube-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  #! your helm values
  values:
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true