apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  type: "oci" # type options are default or oci
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts