apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmRepository.yaml
  - helmRelease.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: flux-system
    unsetOnly: true

# unsetOnly is false by default. When true,
# NamespaceTransformer will only set namespace fields that are currently unset (empty string or missing).
# documentation https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_namespacetransformer_
# We want to keep the helm resources controlled via flux-system namespace but the resources that it is
# deploying we want to not be deployed to the flux-system namespace but what is defined within those resources.