apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      version: '1.15.0'
      sourceRef:
        kind: HelmRepository
        name: harbor
  interval: 5m
  timeout: 5m
  targetNamespace: harbor
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  #! your helm values