apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  type: "default" # options are default or oci
  interval: 5m
  url: https://helm.goharbor.io